#Database Properties
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
   url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
   database-platform: org.hibernate.dialect.MySQLDialect

   properties:
    hibernate:
      format_sql: true
      show_sql: true;
   hibernate:
      ddl-auto: update

mvc:
 hiddenmethod:
   filter:
     enabled: true


logging:
 level:
   org.hibernate.SQL: DEBUG
   org.hibernate.orm.jdbc.bind: TRACE

mail:
 drivetime: "drivetime@example.com"
 host: localhost
 port: 1025
 username: ${MAIL_USER:softuni}
 password: ${MAIL_PASSWORD:softuni}




